### ISSUE TITLE
'vue-cli-service' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by Beattheend** [EsunR/Blog-Index#14]
我已经安装了vue-cli-service并使用vue --version命令检查了cli版本为4.4.4
报错如下：
1.
![QQ截图20200620023849](https://user-images.githubusercontent.com/64207250/85170204-a53cf080-b29f-11ea-8f86-7e1e7f7dec11.png)
2.
![QQ截图202006201023849](https://user-images.githubusercontent.com/64207250/85170188-a110d300-b29f-11ea-9a4f-0f472a620048.png)

是那出现了问题？

**Comment by Beattheend** [comment]
问题已解决，该问题归档
执行：npm cache clean --force
删除：package-lock.json
执行：npm install
执行：npm run build

**Comment by wodepig** [comment]
和你一样的问题,成功解决
