### ISSUE TITLE
希望能出个部署教程

### ISSUE THREAD

**Issue by 2922619853** [EsunR/Blog-Index#22]
不知道怎么在宝塔部署，希望作者大大能出个部署教程，非常感谢

**Comment by EsunR** [comment]
不好意思，因为工作太忙没有时间出更详细教程，可以参考 vue-cli 的文档来了解 vue 项目的 build 流程，请见谅，感谢喜欢这个项目，祝生活愉快

**Comment by 2922619853** [comment]
哈哈哈哈，已经会了，只不过不会写接口



---原始邮件---
发件人: "Rui"<notifications@github.com&gt;
发送时间: 2020年11月25日(周三) 下午2:13
收件人: "EsunR/Blog-Index"<Blog-Index@noreply.github.com&gt;;
抄送: "临江寒"<2922619853@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [EsunR/Blog-Index] 希望能出个部署教程 (#22)




 
不好意思，因为工作太忙没有时间出更详细教程，可以参考 vue-cli 的文档来了解 vue 项目的 build 流程，请见谅，感谢喜欢这个项目，祝生活愉快
