### ISSUE TITLE
没有服务器可以试试github pages做个静态的

### ISSUE THREAD

**Issue by WinterChenS** [EsunR/Blog-Index#40]
如题

**Comment by shenweiyan** [comment]
站点已经打不开了，个人也折腾了一个基于 [hugo](https://github.com/shenweiyan/WebStack-Hugo) 的~

**Comment by MikasaEureka** [comment]
这个不能直接在github-io上用吗

**Comment by EsunR** [comment]
只要把打包出来的html静态资源部署到github io上就可以，具体方案可以自行Google，目前还没有时间写教程。另外本项目master分支目前不再维护，正在使用vue3重构中（dev分支）
