### ISSUE TITLE
大佬，这次出事情了，我换了下node，就一直报错，还回去还是报错

### ISSUE THREAD

**Issue by king-zhangbn** [EsunR/Blog-Index#42]

**Comment by EsunR** [comment]
这个项目比较长时间没有维护了，npm 依赖比较陈旧，安装的时候问题会比较多，如果着急使用就试一下把node版本退回到12以下，并使用cnpm安装依赖。

不过我正在使用 vue3 对这个项目进行重构，不着急的话可以等等，开发完成我会在这个 comment 下留言，感谢喜欢这个项目~
