### ISSUE TITLE
bing图片的api貌似不行了呢

### ISSUE THREAD

**Issue by wodepig** [EsunR/Blog-Index#45]
![image](https://user-images.githubusercontent.com/42103087/157647628-3b8ebad5-bbcc-45ee-b3ef-08683017341f.png)

rt,将 _BACKGROUND_IMG_URL_ 留空后不加载图片.而且纯前端无法解决跨域问题.所以找了个第三方的api接口
图片API:https://www.eee.dog/tech/rand-pic-api.html
另外使用了一言:https://developer.hitokoto.cn/,随机获取一段话
 `自己的小页面搭建ok哈哈,挂上来瞅瞅http://devitem.top/`

**Comment by EsunR** [comment]
感谢建议~ 图片源已替换，另外本项目master分支目前不再维护，正在使用vue3重构中（dev分支）
