### ISSUE TITLE
vercel部署报错

### ISSUE THREAD

**Issue by DevDreamerx** [EsunR/Blog-Index#50]
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:471:10)
    at /vercel/path0/node_modules/webpack/lib/NormalModule.js:503:5
    at /vercel/path0/node_modules/webpack/lib/NormalModule.js:358:12
    at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /vercel/path0/node_modules/cache-loader/dist/index.js:118:7
    at /vercel/path0/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
在网上查了下  应该是node 18不支持旧版本的openssl,我该如何修改配置文件来解决错误呢？

**Comment by GentlemanHu** [comment]
vercel后台设置node版本为16即可
<img width="1337" alt="image" src="https://github.com/EsunR/Blog-Index/assets/34559079/c9cdf21c-f0a8-4344-a80c-e9efb008f810">


> ```
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
>     at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:471:10)
>     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:503:5
>     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:358:12
>     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
>     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
>     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
>     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
>     at context.callback (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
>     at /vercel/path0/node_modules/cache-loader/dist/index.js:118:7
>     at /vercel/path0/node_modules/graceful-fs/graceful-fs.js:61:14
>     at FSReqCallback.oncomplete (node:fs:198:23) {
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
>   library: 'digital envelope routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'
> ```
> 
> 在网上查了下 应该是node 18不支持旧版本的openssl,我该如何修改配置文件来解决错误呢？

**Comment by EsunR** [comment]
package.json 中已锁定 node 版本为 16.x，拉取新的代码部署时 Vercel 检测到后会自动切换回使用 node 16
