### ISSUE TITLE
请问一下还更新吗？分类那个地方手机显示有问题

### ISSUE THREAD

**Issue by kkkouo** [EsunR/Blog-Index#51]
如果分类添加多个的话，手机上显示，分类的名字会竖着显示，要是再多就会挤到一起，请问这个该怎么解决。

**Comment by EsunR** [comment]
这里没有考虑分类过多的溢出显示，一周内在dev分支修复

**Comment by kkkouo** [comment]
> 这里没有考虑分类过多的溢出显示，一周内在dev分支修复

还有就是分类下面的内容过多·切换分类会卡页面。。。

**Comment by EsunR** [comment]
> > 这里没有考虑分类过多的溢出显示，一周内在dev分支修复
> 
> 还有就是分类下面的内容过多·切换分类会卡页面。。。

已在dev分支[支持抽屉的顶部 Tabs 按钮支持左右滑动](https://github.com/EsunR/Blog-Index/commit/2a6ea0082db157cf56dd5a1a84f2f008417b4697)
