### ISSUE TITLE
关于右上角Github页面跳转的问题

### ISSUE THREAD

**Issue by lanthora** [EsunR/Blog-Index#6]
非常喜欢你设计的这个页面，也很尊重你的劳动成果。
但是在右上角的跳转链接很容易被读者误解。
能否将主题的链接放到页面底部，类似与下面的样子

> **Designed By [EsunR](https://github.com/EsunR/Blog-Index)**

**Comment by EsunR** [comment]
你好，建议已采纳，配置文件 `/src/config.js` 下新增了 `GITHUB` 变量与 `FOOTER_INFO` 变量，详见 Readme 中的使用说明
