### ISSUE TITLE
首页中间要是有搜索框就好了

### ISSUE THREAD

**Issue by ruzhefeiyu** [EsunR/Blog-Index#7]
加上搜索框，这就是一个电脑主页，把各个搜索框都搞进来，百度。360等等，满足不同人的需要

**Comment by ghost** [comment]
d

**Comment by EsunR** [comment]
项目的定位仅仅是博客主页的引导页，目前这个功能可能不会考虑，使用本地资源是为了可以方便替换，也可以自行替换静态资源，感谢喜欢这个项目，祝生活愉快
