### ISSUE TITLE
大佬，请问这种图片是怎么制作出来的？

### ISSUE THREAD

**Issue by hyp530** [EsunR/Blog-Index#8]
大佬，可否请教下，这种图片是怎么制作出来的：
https://camo.githubusercontent.com/75d6ae3bfc0005e16ee2aa954c3e397ae7532818/687474703a2f2f6d61726b646f776e2e696d672e6573756e722e78797a2f73686f772e706e67

**Comment by EsunR** [comment]
就是自己用Photoshop抠出来的:P
