### ISSUE TITLE
网址后出现#号

### ISSUE THREAD

**Issue by kurobaryo** [EsunR/Blog-Index#9]
大佬，我很喜欢你的主页，但是能否问下域名后的#能去掉吗，就比如说https://www.esunr.xyz/#/home，谢谢！

**Comment by EsunR** [comment]
可以自行修改vue-router为history模式来达到这一需求，但这需要配置后台服务器来支持，具体可参考：https://router.vuejs.org/zh/guide/essentials/history-mode.html
